---

- hosts: gen-stg_idx-cm
#  serial: 4
  become: yes
  vars:
    user: splunk_localuser
    user_group: wheel
    ansible_user: splunk_localuser
    ansible_ssh_private_key_file: ~/.ssh/splunk-server-ssh.key
    deploy_dir: apps
#    git_project: zero-
    app_packages:
      - { project: 'zero-id', repo: 'zero_idx-cluster', branch: 'GEN-STG_MASTER'}
      - { project: 'zero-id', repo: 'zero_stage', branch: 'master'}
      - { project: 'zero-ed', repo: 'Splunk_TA_nix', branch: 'sz-monitor'}
#    app_decom:
#      - { project: 'zero-id', repo: 'zero_app_mon' }
  roles:
    - configure_host_vars
    - configure_git-management
    - { role: splunk_gen_update-repo-apps, when: result|changed }
#    - { role: splunk_gen_decom-apps, when: result|changed }
    - { role: splunk_gen_restart, when: result|changed }
# listed apps from ITSI 2.6.0 make sure to add apps that are added in later builds
#    clustered_splunk_apps: [ 'SA-ITSI-CustomModuleViz', 'DA-ITSI-STORAGE', 'DA-ITSI-APPSERVER', 'DA-ITSI-DATABASE', 'DA-ITSI-EUEM', 'DA-ITSI-LB', 'DA-ITSI-OS', 'DA-ITSI-VIRTUALIZATION', 'DA-ITSI-WEBSERVER', 'DA-ITSI-WebServices', 'itsi', 'SA-IndexCreation', 'SA-ITOA', 'SA-ITSI-ATAD', 'SA-ITSI-Licensechecker', 'SA-ITSI-MetricAD', 'SA-UserAccess', 'Splunk_SA_CIM', 'Splunk_TA_webservices' ]
